FROM maven:3.5 as buider
WORKDIR /app
COPY pom.xml app/
RUN pwd
RUN ls -al
RUN mvn clean package 

FROM tomcat:8-jre8
WORKDIR /app
COPY --from=builder /app/target/hiapp.war /usr/local/tomcat/webapps/
EXPOSE 8080
